name: Windows
on:
  pull_request:

jobs:
  build:
    name: Window CI
    env:
      LIBRARY_NAME: gz-rendering
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v4
      with:
        path: tmp/gz-rendering
    - name: Determine major version
      shell: bash
      run: |
        curl -LO https://raw.githubusercontent.com/gazebo-tooling/release-tools/master/jenkins-scripts/tools/detect_cmake_major_version.py
        echo PACKAGE="$LIBRARY_NAME$(python3 detect_cmake_major_version.py tmp/gz-rendering/CMakeLists.txt)" >> $GITHUB_ENV
    - name: setup-pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        run-install: false

    - name: Install build tools
      run: |
        pixi init
        pixi add vcstool colcon-common-extensions pkgconfig
    - name: Setup pixi env variables
      shell: bash
      run: |
        eval "$(pixi shell-hook)"
        echo CMAKE_PREFIX_PATH=$CONDA_PREFIX\\Library >> $GITHUB_ENV
    - name: Install base dependencies
      run: |
        # List adapted from https://github.com/gazebo-tooling/release-tools/blob/f89ac8cafc646260598eb8eb6d94be8093bdc9f7/jenkins-scripts/lib/windows_env_vars.bat#L22
        pixi add assimp dlfcn-win32 eigen ffmpeg freeimage gdal gflags ogre ogre-next spdlog tinyxml2
    - name: Clone source dependencies
      shell: bash
      run: |
        mkdir src
        cd src
        pixi run vcs import --input https://raw.githubusercontent.com/gazebo-tooling/gazebodistro/master/$PACKAGE.yaml
        rm -rf gz-rendering
        # Move the gz-rendering we checkout earlier and replace the one cloned by vcs
        mv ../tmp/gz-rendering .

    - name: Build Dependencies
      run: |
        pixi run colcon build --merge-install --cmake-args -G"Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF  --event-handlers console_direct+ --packages-up-to ${env:PACKAGE}

    - name: Build Package
      run: pixi run colcon build --merge-install --cmake-args -G"Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DSKIP_ogre=ON --event-handlers console_direct+ --packages-select ${env:PACKAGE}

    - name: Test
      run: pixi run colcon test --merge-install --event-handlers console_direct+ --packages-select ${env:PACKAGE}
